// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB0uBwnjldj1FagTbI1YKCZXP3INY6pAI',
    appId: '1:278304563570:web:5444a45b16b28f9d87bdeb',
    messagingSenderId: '278304563570',
    projectId: 'bazz-ja96',
    authDomain: 'bazz-ja96.firebaseapp.com',
    storageBucket: 'bazz-ja96.firebasestorage.app',
    measurementId: 'G-65T1SPHM72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1RnqnwH7qw9HnzPZTbAWikWQvoMEIifs',
    appId: '1:278304563570:android:c41c13614d6391c987bdeb',
    messagingSenderId: '278304563570',
    projectId: 'bazz-ja96',
    storageBucket: 'bazz-ja96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGY3G-5KkQwU6k3VHwGvZjL-ZOvXpA4jw',
    appId: '1:278304563570:ios:91cdefed7bb6a40687bdeb',
    messagingSenderId: '278304563570',
    projectId: 'bazz-ja96',
    storageBucket: 'bazz-ja96.firebasestorage.app',
    iosBundleId: 'com.bazz.bazzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGY3G-5KkQwU6k3VHwGvZjL-ZOvXpA4jw',
    appId: '1:278304563570:ios:91cdefed7bb6a40687bdeb',
    messagingSenderId: '278304563570',
    projectId: 'bazz-ja96',
    storageBucket: 'bazz-ja96.firebasestorage.app',
    iosBundleId: 'com.bazz.bazzApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB0uBwnjldj1FagTbI1YKCZXP3INY6pAI',
    appId: '1:278304563570:web:4e992bee2f18858f87bdeb',
    messagingSenderId: '278304563570',
    projectId: 'bazz-ja96',
    authDomain: 'bazz-ja96.firebaseapp.com',
    storageBucket: 'bazz-ja96.firebasestorage.app',
    measurementId: 'G-2LMZ01DLTX',
  );
}
