# ============================================
# BazZ Platform — pnpm Workspace
# ============================================
# Defines which directories are workspace packages
# pnpm will hoist shared dependencies and link local packages

packages:
  - "apps/api"
  - "apps/merchant-app"
  - "apps/admin"
  - "apps/web"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@tailwindcss/oxide': true
  esbuild: true
  prisma: true
  protobufjs: true
